name: Build Flutter APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Upgrade Project to Android v2 Embedding
        run: |
          # Injection automatique de la configuration moderne v2 dans le fichier AndroidManifest.xml
          MANIFEST_PATH="android/app/src/main/AndroidManifest.xml"
          if [ -f "$MANIFEST_PATH" ]; then
            sed -i '/<activity/a \            <meta-data android:name="flutterEmbedding" android:value="2" />' "$MANIFEST_PATH"
          fi

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release
